version: '3.7'
services:
  secureworks:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - "dbdata:/var/lib/data/"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 5
#  dynamodb:
#    image: "cnadiminti/dynamodb-local"
#    ports:
#      - "8000:8000"
#    volumes:
#      - "dynamodata:/dynamodb_local_db"

volumes:
  dynamodata:
  dbdata: